export const books: Book[] = [
  {
    title: "Read Write Own",
    author: "Chris Dixon",
    date: "2024-03-06",
    link: "https://www.amazon.com/Read-Write-Own-Building-Internet/dp/0593731387",
    slug: "read-write-own",
    rating: 8.2,
  },
  {
    title: "American Kingpin",
    author: "Nick Bilton",
    date: "2024-02-10",
    link: "https://www.amazon.com/American-Kingpin-Nick-Bilton-audiobook/dp/B06Y1QXMXX",
    slug: "american-kingpin",
    rating: 8.5,
  },
  {
    title: "Elon Musk",
    author: "Water Isaacson",
    date: "2023-12-02",
    link: "https://www.amazon.com/Audible-Elon-Musk/dp/B0BX4S57GM",
    slug: "elon-musk-walter-isaacson",
    rating: 6.4,
  },
  {
    title: "The Wager",
    author: "David Grann",
    date: "2023-01-14",
    link: "https://www.amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/dp/B0B9T7F9RR",
    slug: "the-wager",
    rating: 8.7,
  },
  {
    title: "Philosophy for Polar Explorers",
    author: "Erling Kagge",
    date: "2023-12-20",
    link: "https://www.amazon.com/Philosophy-for-Polar-Explorers/dp/B085J1JT2F",
    slug: "philosophy-for-polar-explorers",
    rating: 9.0,
  },
  // {
  //   title: "Alchemy",
  //   author: "Rory Sutherland",
  //   date: "2023-07-30",
  //   link: "https://www.amazon.com/Alchemy-Rory-Sutherland-audiobook/dp/B07PQTT7B4",
  //   slug: "alchemy-rory-sutherland",
  //   rating: 7.7,
  // },
  // {
  //   title: "Stillness is the Key",
  //   author: "Ryan Holiday",
  //   date: "2023-10-21",
  //   link: "https://www.amazon.com/Stillness-Is-Key-Ryan-Holiday-audiobook/dp/B07QR7LMXR",
  //   slug: "stillness-is-the-key",
  //   rating: 8.5,
  // },
  // {
  //   title: "Wool",
  //   author: "Hugh Howey",
  //   date: "2023-09-04",
  //   link: "https://www.amazon.com/Wool-Silo-Saga-Book-1/dp/B0BKR8VBYV",
  //   slug: "wool-hugh-howey",
  //   rating: 8,
  // },
  // {
  //   title: "In Order to Live",
  //   author: "Yeonmi Park",
  //   date: "2023-04-12",
  //   link: "https://www.amazon.com/In-Order-to-Live-Yeonmi-Park-audiobook/dp/B0143PGHEU",
  //   slug: "in-order-to-live",
  //   rating: 8.8,
  // },
  // {
  //   title: "Permanent Record",
  //   author: "Edward Snowden",
  //   date: "2022-06-26",
  //   link: "https://www.amazon.com/Permanent-Record-Edward-Snowden-audiobook/dp/B07VZWH6NB",
  //   slug: "permanent-record",
  //   rating: 8.3,
  // },
  // {
  //   title: "The Black Swan",
  //   author: "Nassim Nicholas Taleb",
  //   date: "2022-05-01",
  //   link: "https://www.amazon.com/Black-Swan-Second-Improbable-Robustness/dp/B07KRM6L52",
  //   slug: "the-black-swan",
  //   rating: 8.9,
  // },
  // {
  //   title: "Anti-Fragile",
  //   author: "Nassim Nicholas Taleb",
  //   date: "2022-07-12",
  //   link: "https://www.amazon.com/Antifragile-Nassim-Nicholas-Taleb-audiobook/dp/B00A2ZIZYQ",
  //   slug: "anti-fragile",
  //   rating: 7.7,
  // },
  // {
  //   title: "A Random Walk Down Wall Street",
  //   author: "Burton Malkiel",
  //   date: "2021-05-14",
  //   link: "https://www.amazon.com/Random-Walk-Down-Wall-Street/dp/B07MWDML9V",
  //   slug: "a-random-walk-down-wall-street",
  //   rating: 7.4,
  // },
  // {
  //   title: "Solve for Happy",
  //   author: "Mo Gawdat",
  //   date: "2022-09-09",
  //   link: "https://www.amazon.com/Solve-for-Happy-Mo-Gawdat-audiobook/dp/B01MZBNK5K",
  //   slug: "solve-for-happy",
  //   rating: 9.2,
  // },
  // {
  //   title: "Shoe Dog",
  //   author: "Phil Knight",
  //   date: "2021-11-26",
  //   link: "https://www.amazon.com/Shoe-Dog-Phil-Knight-audiobook/dp/B01CRJA470",
  //   slug: "shoe-dog-phil-knight",
  //   rating: 7.0,
  // },
  // {
  //   title: "The Goal",
  //   author: "Elieyahu Goldratt",
  //   date: "2021-12-30",
  //   link: "https://www.amazon.com/The-Goal-audiobook/dp/B00IFGGDA2",
  //   slug: "the-goal-elieyahu-goldratt",
  //   rating: 7.5,
  // },
  // {
  //   title: "Everybody Lies",
  //   author: "Seth Stephens-Davidowitz",
  //   date: "2022-01-08",
  //   link: "https://www.amazon.com/Everybody-Lies-audiobook/dp/B06XCYD5KG",
  //   slug: "everybody-lies",
  //   rating: 6.8,
  // },
];
